import calendar
m,d,y=(int(i) for i in  input().split())
x=calendar.weekday(y,m,d)
if(x==0): print("MONDAY")
elif(x==1): print("TUESDAY")
elif(x==2): print("WEDNESDAY")
elif(x==3): print("THURSDAY")
elif(x==4): print("FRIDAY")
elif(x==5): print("SATURDAY")
else: print("SUNDAY")
